#!/bin/sh

fail() {
    echo "$@"
    exit 1
}

if [ $# -lt 1 ] ; then
cat <<EOT 1>&2
Usage: $0 <ELF image to boot> [options to pass to qemu]

This script should live in a directory that also contains beagle_create_image.
EOT
    exit 1
fi

INPUT_FILE="$1"

# Find out where this script is kept.
BASE_PATH=$(dirname $(readlink -f $0))

f=$(mktemp)
$BASE_PATH/beagle_create_image "$1" "$f" || exit 1

qemu-omap3 -M beagle -nographic -mtdblock "$f" "$@" 

rm -f "$f"

