#!/bin/sh

fail() {
    echo "$@" 1>&2
    exit 1
}

if [ $# -ne 2 ] ; then
cat <<EOT 1>&2
Usage: $0 <ELF image to boot> <output image file>

This script should live in a directory that also contains the relevant files
x-load.bin.ift and u-boot.bin.

EOT
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="$2"

[ -r "$INPUT_FILE" ] || fail "Cannot read input ELF file."

# Find out where this script is kept.
BASE_PATH=$(dirname $(readlink -f $0))

dd if="$BASE_PATH/x-load.bin.ift" of="$OUTPUT_FILE" seek=0 bs=2048 2>/dev/null \
    || fail "Failed to copy x-load into image."
dd if="$BASE_PATH/u-boot.bin" of="$OUTPUT_FILE" seek=256 bs=2048 conv=notrunc 2>/dev/null \
    || fail "Failed to copy u-boot into image."
dd if="$INPUT_FILE" of="$OUTPUT_FILE" seek=1280 bs=2048 conv=notrunc 2>/dev/null\
    || fail "Failed to copy ELF into image."
dd if=/dev/zero of="$OUTPUT_FILE" bs=2048 count=2 oflag=append conv=notrunc 2>/dev/null\
    || fail "Failed to add padding to image."

size=$(wc -c < "$INPUT_FILE" | awk '{print $1}')
size=$(printf "%08x" $size)

# There is a string in the environment that is needs to be replaced with the
# image size.
sed -i -e "s/SIZEPLZZ/$size/g" "$OUTPUT_FILE"

